git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      
language: c

script:
- ls
- ./build-tools 
- bash ./marsh build --markdown="tools/local/bin/markdown"
- cd public
- tar cvzf docs.tar.gz docs/
